source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CHVIpify_Example' do
  pod "CHVIpify", :path => "../"
end

target 'CHVIpify_Tests' do
  pod "CHVIpify", :path => "../"

  
end
